In [11]:
# http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_RGB.html

import numpy as np

AdobeD50_2_XYZ = np.array([
 0.6097559,  0.2052401,  0.1492240,
 0.311124,  0.6256560,  0.0632197,
 0.0194811,  0.0608902 , 0.7448387]).reshape(3,3)

XYZ_2_AdobeD65 = np.array([
 2.0413690, -0.5649464, -0.3446944,
-0.9692660,  1.8760108,  0.0415560,
 0.0134474, -0.1183897,  1.0154096]).reshape(3,3)



D50_2_D65 = AdobeD50_2_XYZ @ XYZ_2_AdobeD65

D50_2_D65

array([[ 1.04781122,  0.02288666, -0.050127  ],
       [ 0.02954194,  0.99048447, -0.01704905],
       [-0.00923454,  0.01504367,  0.75213169]])

In [14]:
# AppleD50_2_XYZ = np.array([
# ]).reshape(3,3)

XYZ_2_AppleD65 = np.array([
 2.9515373, -1.2894116, -0.4738445,
-1.0851093,  1.9908566,  0.0372026,
 0.0854934, -0.2694964,  1.0912975
]).reshape(3,3)




AppleD50_2_XYZ = np.array([
 0.4755678,  0.3396722,  0.1489800,
 0.2551812,  0.6725693,  0.0722496,
 0.0184697,  0.1133771,  0.6933632]).reshape(3,3)

Apple_D50_2_D65 = AppleD50_2_XYZ @ XYZ_2_AppleD65
Apple_D50_2_D65

array([[ 1.04781144,  0.02288643, -0.050127  ],
       [ 0.02954249,  0.99048442, -0.01704907],
       [-0.00923456,  0.01504362,  0.75213168]])

In [21]:
AppleD50_2_XYZ @ [1,1,1]  # should be D50 XYZ coord


array([0.96422  , 1.0000001, 0.82521  ])

In [22]:
AdobeD50_2_XYZ @ [1,1,1]

array([0.96422  , 0.9999997, 0.82521  ])

In [24]:
XYZ_2_AppleD65 @ [0.95047,	1.00000,	1.08883] #  D65 XYZ should be 1

array([0.99999995, 1.00000007, 0.99999997])

In [27]:
# https://www.russellcottrell.com/photo/matrixCalculator.htm

RGB2XYZ = np.array(
[[ 0.4866327,  0.2656632,  0.1981742],
 [ 0.2290036,  0.6917267,  0.0792697],
 [ 0.0000000,  0.0451126,  1.0437174]])

source_dest_white =np.array(
[[ 1.0478400,  0.0228979, -0.0501808],
 [ 0.0295537,  0.9904924, -0.0170663],
 [-0.0092459,  0.0150633,  0.7518389]]
)

XYZ2RGB = np.array(
[[ 2.4931808, -0.9312655, -0.4026597],
 [-0.8295031,  1.7626941,  0.0236251],
 [ 0.0358536, -0.0761890,  0.9570926]]
2)

In [33]:
source_dest_white @ [0.95047,	1.00000,	1.08883]

array([0.96420002, 1.00000001, 0.8249001 ])

In [31]:
source_dest_white @ XYZ2RGB

array([[ 2.59166153, -0.93163202, -0.46940965],
       [-0.74854569,  1.71971303, -0.00483363],
       [-0.00859062, -0.02211948,  0.72365827]])