In [2]:
import numpy as np
import xml.etree.ElementTree as ET


In [ ]:
# FM Forward Matrix
# CM Color Matrix


In [13]:
class DCPMatrixParser:
    def __init__(self, file_path):
        self.file_path = file_path
        self.matrices = {}

    def parse_matrices(self):
        tree = ET.parse(self.file_path)
        root = tree.getroot()
        for matrix_elem in root.findall('*'):
            if 'Matrix' in matrix_elem.tag:
                matrix_name = matrix_elem.tag
                rows = int(matrix_elem.attrib['Rows'])
                cols = int(matrix_elem.attrib['Cols'])
                matrix = np.zeros((rows, cols))
                for element in matrix_elem.findall('Element'):
                    row = int(element.attrib['Row'])
                    col = int(element.attrib['Col'])
                    value = float(element.text)
                    matrix[row][col] = value
                self.matrices[matrix_name] = matrix

    def save_matrices(self, output_file_path):
        tree = ET.parse(self.file_path)
        root = tree.getroot()
        for matrix_elem in root.findall('*'):
            if matrix_elem.tag in self.matrices:
                matrix = self.matrices[matrix_elem.tag]
                for element in matrix_elem.findall('Element'):
                    row = int(element.attrib['Row'])
                    col = int(element.attrib['Col'])
                    element.text = str(matrix[row][col])

        tree.write(output_file_path, encoding='utf-8', xml_declaration=True)


# Usage
parser = DCPMatrixParser('E:\摄影Photo软件工具\DCP_Projects\dcp转换工具20200618\Sony ILCE-7RM2 Adobe Standard.xml')
parser.parse_matrices()
parser.matrices['ColorMatrix1'] = np.zeros((3,3))
# Modify matrices if needed
parser.save_matrices('./output.xml')

In [10]:
parser.matrices

{'ColorMatrix1': array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 'ColorMatrix2': array([[ 0.6629, -0.19  , -0.0483],
        [-0.4618,  1.2349,  0.255 ],
        [-0.0622,  0.1381,  0.6514]]),
 'ForwardMatrix1': array([[ 0.951 , -0.1409,  0.0151],
        [-0.284 ,  1.0161,  0.2678],
        [-0.0232,  0.2213,  0.7661]]),
 'ForwardMatrix2': array([[5.405e-01, 2.586e-01, 1.653e-01],
        [3.122e-01, 6.366e-01, 5.120e-02],
        [1.445e-01, 2.000e-04, 6.804e-01]]),
 'ReductionMatrix1': array([], shape=(0, 0), dtype=float64),
 'ReductionMatrix2': array([], shape=(0, 0), dtype=float64)}

In [3]:
xml_data = '''
<ColorMatrix1 Rows="3" Cols="3">
    <Element Row="2" Col="2">0.717700</Element>
    <Element Row="2" Col="1">0.098100</Element>
    <Element Row="2" Col="0">-0.040800</Element>
    <Element Row="1" Col="2">0.192800</Element>
    <Element Row="1" Col="1">1.324600</Element>
    <Element Row="1" Col="0">-0.501600</Element>
    <Element Row="0" Col="2">-0.041900</Element>
    <Element Row="0" Col="1">-0.216800</Element>
    <Element Row="0" Col="0">0.698500</Element>
</ColorMatrix1>
'''

# Parse XML data
root = ET.fromstring(xml_data)
rows = int(root.attrib['Rows'])
cols = int(root.attrib['Cols'])
matrix = np.zeros((rows, cols))

for element in root.findall('Element'):
    row = int(element.attrib['Row'])
    col = int(element.attrib['Col'])
    value = float(element.text)
    matrix[row][col] = value

print(matrix)

[[ 0.6985 -0.2168 -0.0419]
 [-0.5016  1.3246  0.1928]
 [-0.0408  0.0981  0.7177]]


In [6]:
row

0

In [7]:
# For sony CM1





A = np.array([0.663700,0.203800,0.096800,0.276800,0.804300,-0.081200,0.025900,-0.216100,1.015300])
A = A.reshape(3,3)

In [1]:
 <Element Row="2" Col="2">0.717700</Element>
    <Element Row="2" Col="1">0.098100</Element>
    <Element Row="2" Col="0">-0.040800</Element>
    <Element Row="1" Col="2">0.192800</Element>
    <Element Row="1" Col="1">1.324600</Element>
    <Element Row="1" Col="0">-0.501600</Element>
    <Element Row="0" Col="2">-0.041900</Element>
    <Element Row="0" Col="1">-0.216800</Element>
    <Element Row="0" Col="0">0.698500</Element>






NameError: name 'np' is not defined

In [10]:
x.shape

(3,)